#!/usr/bin/env bash
# M4.1 §8.2 — canonical lock recompilation and drift detection.
#
# Usage:
#   scripts/compile_lock.sh            # recompile requirements.lock in place
#   scripts/compile_lock.sh --verify   # recompile twice, verify reproducibility
#                                       # and that the committed lock has no drift
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

REQUIREMENTS_FILE="requirements.txt"
LOCK_FILE="requirements.lock"
EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"

# uv's autogenerated header is two lines: a fixed banner, then the exact
# invocation with the `-o` argument (an absolute, host/OS-specific mktemp
# path when we compile to a scratch file) at the end. We pin both lines to
# an exact/bounded grammar so any drift in uv's header format — moved
# banner, changed flags, `-o` not last, a second banner — is rejected
# instead of silently leaving the scratch path (or nothing) in place.
HEADER_LINE1="# This file was autogenerated by uv via the following command:"
HEADER_PREFIX="#    uv pip compile ${REQUIREMENTS_FILE} --index-strategy unsafe-best-match --generate-hashes --no-annotate -o "

canonical_header_line2() {
  printf '%s%s' "$HEADER_PREFIX" "$LOCK_FILE"
}

# Fail closed if $1 has any comment/header line beyond the fixed two-line
# header — i.e. line 3 onward must be the first body line, never another
# `#`-prefixed line. This is the single shared boundary that rejects both
# an arbitrary unexpected third header/comment line and a duplicated
# autogenerated-by banner (which is itself just another `#`-prefixed line),
# reused by both the freshly-compiled output and the committed lock so the
# two checks cannot drift apart from each other.
assert_no_extra_header_lines() {
  local file="$1"
  local extra_line
  extra_line="$(awk 'NR>=3 && $0 ~ /^#/ {print NR; exit}' "$file")"
  if [ -n "$extra_line" ]; then
    echo "compile_lock.sh: $file has an unexpected header/comment line at line $extra_line (expected exactly two header lines, line 3 must be the first body line)" >&2
    return 1
  fi
}

# Validate that $1's header matches the exact/bounded uv grammar above, then
# normalize its `-o <path>` line 2 to the canonical, host/platform-independent
# form. Fails closed (nonzero exit, scratch file left untouched) on any
# mismatch: missing header, wrong banner, `-o` missing or not the final
# token, or any extra comment/header line (including a duplicated banner)
# beyond the fixed two-line header.
validate_and_normalize_header() {
  local out="$1"
  local line1 line2 out_arg

  line1="$(sed -n '1p' "$out")"
  if [ "$line1" != "$HEADER_LINE1" ]; then
    echo "compile_lock.sh: uv output header line 1 does not match the expected autogenerated-by banner (got: ${line1:-<empty>})" >&2
    return 1
  fi

  line2="$(sed -n '2p' "$out")"
  case "$line2" in
    "${HEADER_PREFIX}"*)
      out_arg="${line2#"$HEADER_PREFIX"}"
      if [ -z "$out_arg" ] || [ "${out_arg%% *}" != "$out_arg" ]; then
        echo "compile_lock.sh: uv output header line 2 -o argument is empty or has unexpected trailing tokens (got: $line2)" >&2
        return 1
      fi
      ;;
    *)
      echo "compile_lock.sh: uv output header line 2 does not match the expected canonical command prefix (got: ${line2:-<empty>})" >&2
      return 1
      ;;
  esac

  assert_no_extra_header_lines "$out"

  awk -v n=2 -v repl="$(canonical_header_line2)" 'NR==n { print repl; next } { print }' "$out" > "${out}.hdr"
  mv "${out}.hdr" "$out"

  line2="$(sed -n '2p' "$out")"
  if [ "$line2" != "$(canonical_header_line2)" ]; then
    echo "compile_lock.sh: header normalization did not produce the canonical line (got: ${line2:-<empty>})" >&2
    return 1
  fi
}

compile_once() {
  local out="$1"
  uv pip compile "$REQUIREMENTS_FILE" \
    --extra-index-url "$EXTRA_INDEX_URL" \
    --index-strategy unsafe-best-match \
    --generate-hashes --no-annotate \
    -o "$out" >/dev/null
  validate_and_normalize_header "$out"
}

# Strip the leading `^#` comment header (autogenerated-by command/timestamp
# lines) so two runs compare on body only.
canonical_body() {
  awk 'BEGIN{skipping=1} { if (skipping && $0 ~ /^#/) next; skipping=0; print }' "$1"
}

# Fail closed if $1's own header does not match the exact canonical form
# (used against the committed lock file, which body-only comparison would
# otherwise never look at).
validate_committed_header() {
  local file="$1"
  local line1 line2

  line1="$(sed -n '1p' "$file")"
  if [ "$line1" != "$HEADER_LINE1" ]; then
    echo "compile_lock.sh: committed $file header line 1 does not match the canonical autogenerated-by banner (got: ${line1:-<empty>})" >&2
    return 1
  fi

  line2="$(sed -n '2p' "$file")"
  if [ "$line2" != "$(canonical_header_line2)" ]; then
    echo "compile_lock.sh: committed $file header line 2 is not the canonical command (got: ${line2:-<empty>}; expected: $(canonical_header_line2))" >&2
    return 1
  fi

  assert_no_extra_header_lines "$file"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

mode="${1:-compile}"

tmp_a="$(mktemp)"
tmp_b="$(mktemp)"
trap 'rm -f "$tmp_a" "$tmp_b" "${tmp_a}.body" "${tmp_b}.body"' EXIT

compile_once "$tmp_a"
compile_once "$tmp_b"

canonical_body "$tmp_a" > "${tmp_a}.body"
canonical_body "$tmp_b" > "${tmp_b}.body"
hash_a="$(sha256_of "${tmp_a}.body")"
hash_b="$(sha256_of "${tmp_b}.body")"

if [ "$hash_a" != "$hash_b" ]; then
  echo "compile_lock.sh: lock is not reproducible (two runs produced different bodies)" >&2
  exit 1
fi

if [ "$mode" = "--verify" ]; then
  if [ ! -f "$LOCK_FILE" ]; then
    echo "compile_lock.sh: $LOCK_FILE does not exist" >&2
    exit 1
  fi
  validate_committed_header "$LOCK_FILE"
  canonical_body "$LOCK_FILE" > "${LOCK_FILE}.body"
  hash_committed="$(sha256_of "${LOCK_FILE}.body")"
  rm -f "${LOCK_FILE}.body"
  if [ "$hash_committed" != "$hash_a" ]; then
    echo "compile_lock.sh: committed $LOCK_FILE has drifted from requirements.txt" >&2
    exit 1
  fi
  echo "compile_lock.sh: --verify PASS (reproducible, no drift)"
else
  cp "$tmp_a" "$LOCK_FILE"
  echo "compile_lock.sh: wrote $LOCK_FILE"
fi
