#!/usr/bin/env bash
# M4.1 §8.2 — canonical lock recompilation and drift detection.
#
# Usage:
#   scripts/compile_lock.sh            # recompile requirements.lock in place
#   scripts/compile_lock.sh --verify   # recompile twice, verify reproducibility
#                                       # and that the committed lock has no drift
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

REQUIREMENTS_FILE="requirements.txt"
LOCK_FILE="requirements.lock"
EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"

compile_once() {
  local out="$1"
  uv pip compile "$REQUIREMENTS_FILE" \
    --extra-index-url "$EXTRA_INDEX_URL" \
    --index-strategy unsafe-best-match \
    --generate-hashes --no-annotate \
    -o "$out" >/dev/null
}

# Strip the leading `^#` comment header (autogenerated-by command/timestamp
# lines) so two runs compare on body only.
canonical_body() {
  awk 'BEGIN{skipping=1} { if (skipping && $0 ~ /^#/) next; skipping=0; print }' "$1"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

mode="${1:-compile}"

tmp_a="$(mktemp)"
tmp_b="$(mktemp)"
trap 'rm -f "$tmp_a" "$tmp_b" "${tmp_a}.body" "${tmp_b}.body"' EXIT

compile_once "$tmp_a"
compile_once "$tmp_b"

canonical_body "$tmp_a" > "${tmp_a}.body"
canonical_body "$tmp_b" > "${tmp_b}.body"
hash_a="$(sha256_of "${tmp_a}.body")"
hash_b="$(sha256_of "${tmp_b}.body")"

if [ "$hash_a" != "$hash_b" ]; then
  echo "compile_lock.sh: lock is not reproducible (two runs produced different bodies)" >&2
  exit 1
fi

if [ "$mode" = "--verify" ]; then
  if [ ! -f "$LOCK_FILE" ]; then
    echo "compile_lock.sh: $LOCK_FILE does not exist" >&2
    exit 1
  fi
  canonical_body "$LOCK_FILE" > "${LOCK_FILE}.body"
  hash_committed="$(sha256_of "${LOCK_FILE}.body")"
  rm -f "${LOCK_FILE}.body"
  if [ "$hash_committed" != "$hash_a" ]; then
    echo "compile_lock.sh: committed $LOCK_FILE has drifted from requirements.txt" >&2
    exit 1
  fi
  echo "compile_lock.sh: --verify PASS (reproducible, no drift)"
else
  cp "$tmp_a" "$LOCK_FILE"
  echo "compile_lock.sh: wrote $LOCK_FILE"
fi
