"""M4.1 §8.2 / CR-HCI4-MAJ-01 — `scripts/compile_lock.sh` header canonicalization
must fail closed.

Code_Review_Hosted_CI_Remediation_4.md flagged that the header-normalizing
`awk` substitution added in the prior remediation silently no-ops when uv's
autogenerated header does not match the expected `-o <path>` shape (moved
banner, changed flags, `-o` not the last token, a duplicated banner, or no
`-o` at all) — the script would still exit 0 with a scratch mktemp path
baked into the "canonical" lock, and `--verify` would never notice because
it only ever compares lock *bodies*, never header shape.

These tests drive `scripts/compile_lock.sh` against a fake `uv` binary
(no network, no real package resolution) that emits a chosen header shape,
so the fail-closed behavior is pinned deterministically rather than relying
on uv's actual output format.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_RELPATH = "scripts/compile_lock.sh"

CANONICAL_LINE1 = "# This file was autogenerated by uv via the following command:"
CANONICAL_PREFIX = (
    "#    uv pip compile requirements.txt --index-strategy unsafe-best-match "
    "--generate-hashes --no-annotate -o "
)
BODY = (
    "aiohappyeyeballs==2.7.1 \\\n"
    "    --hash=sha256:065665c041c42a5938ed220bdcd7230f22527fbec085e1853d2402c8a3615d9d\n"
)

FAKE_UV_TEMPLATE = r"""#!/usr/bin/env bash
set -euo pipefail

out=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-o" ]; then
    out="$arg"
  fi
  prev="$arg"
done
if [ -z "$out" ]; then
  echo "fake uv: no -o argument found" >&2
  exit 1
fi

banner="# This file was autogenerated by uv via the following command:"
prefix="#    uv pip compile requirements.txt --index-strategy unsafe-best-match --generate-hashes --no-annotate -o "
body='__BODY__'

scenario="${FAKE_UV_SCENARIO:-success}"

case "$scenario" in
  success)
    { printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out"; printf '%s' "$body"; } > "$out"
    ;;
  missing_header)
    printf '%s' "$body" > "$out"
    ;;
  wrong_banner)
    { printf '%s\n' "# Generated by some other tool entirely"; printf '%s%s\n' "$prefix" "$out"; printf '%s' "$body"; } > "$out"
    ;;
  missing_o_flag)
    { printf '%s\n' "$banner"; printf '#    uv pip compile requirements.txt --index-strategy unsafe-best-match --generate-hashes --no-annotate\n'; printf '%s' "$body"; } > "$out"
    ;;
  trailing_after_o)
    { printf '%s\n' "$banner"; printf '%s%s --unexpected-flag\n' "$prefix" "$out"; printf '%s' "$body"; } > "$out"
    ;;
  empty_o_value)
    { printf '%s\n' "$banner"; printf '%s\n' "$prefix"; printf '%s' "$body"; } > "$out"
    ;;
  duplicate_header)
    {
      printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out";
      printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out";
      printf '%s' "$body";
    } > "$out"
    ;;
  header_moved)
    { printf '\n'; printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out"; printf '%s' "$body"; } > "$out"
    ;;
  unexpected_third_header)
    { printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out"; printf '%s\n' "# unexpected third header line"; printf '%s' "$body"; } > "$out"
    ;;
  record_preseed)
    # Captures a single-line fingerprint (byte count) of whatever content
    # was already sitting at $out *before* this invocation truncates it
    # via `> "$out"` — proves (or disproves) whether the caller seeded the
    # output file with the committed lock ahead of invoking uv, exactly
    # the way real `uv pip compile` treats a pre-existing `-o` file as a
    # version preference. A byte count (not the raw multi-line content) so
    # the recorded line can never itself look like a second `#`-prefixed
    # header line and trip the unrelated header-shape checks below.
    preseed_len="EMPTY"
    if [ -s "$out" ]; then
      preseed_len="$(wc -c < "$out" | tr -d ' ')"
    fi
    { printf '%s\n' "$banner"; printf '%s%s\n' "$prefix" "$out"; printf 'PRESEED_LEN:%s\n' "$preseed_len"; printf '%s' "$body"; } > "$out"
    ;;
  *)
    echo "fake uv: unknown FAKE_UV_SCENARIO '$scenario'" >&2
    exit 1
    ;;
esac
"""


@pytest.fixture()
def fake_repo(tmp_path: Path) -> Path:
    """A minimal fake repo containing only what `compile_lock.sh` touches:
    itself (so `cd "$(dirname BASH_SOURCE)/.."` lands here, not the real
    repo), a placeholder `requirements.txt`, and no `requirements.lock` yet.
    """
    repo = tmp_path / "repo"
    (repo / "scripts").mkdir(parents=True)
    shutil.copy(REPO_ROOT / SCRIPT_RELPATH, repo / SCRIPT_RELPATH)
    (repo / SCRIPT_RELPATH).chmod(0o755)
    (repo / "requirements.txt").write_text("aiohappyeyeballs==2.7.1\n", encoding="utf-8")
    return repo


@pytest.fixture()
def fake_uv_bin(tmp_path: Path) -> Path:
    bin_dir = tmp_path / "fakebin"
    bin_dir.mkdir()
    fake_uv = bin_dir / "uv"
    fake_uv.write_text(FAKE_UV_TEMPLATE.replace("__BODY__", BODY.rstrip("\n")), encoding="utf-8")
    fake_uv.chmod(fake_uv.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return bin_dir


def _run(repo: Path, fake_uv_bin: Path, scenario: str, mode: str | None = None):
    env = dict(os.environ)
    env["PATH"] = f"{fake_uv_bin}:{env['PATH']}"
    env["FAKE_UV_SCENARIO"] = scenario
    argv = ["bash", str(repo / SCRIPT_RELPATH)]
    if mode:
        argv.append(mode)
    return subprocess.run(argv, cwd=repo, capture_output=True, text=True, timeout=60, env=env)


def _canonical_line2() -> str:
    return f"{CANONICAL_PREFIX}requirements.lock"


class TestCompileModeHeaderContract:
    def test_success_scenario_normalizes_header_and_writes_lock(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        result = _run(fake_repo, fake_uv_bin, "success")
        assert result.returncode == 0, result.stderr

        lock_text = (fake_repo / "requirements.lock").read_text(encoding="utf-8")
        lines = lock_text.splitlines()
        assert lines[0] == CANONICAL_LINE1
        assert lines[1] == _canonical_line2()
        assert "aiohappyeyeballs==2.7.1" in lock_text

    def test_success_scenario_is_stable_across_repeated_runs(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        """The canonical header must not depend on the scratch mktemp path
        chosen by any given run — repeated compiles must byte-for-byte
        agree on the header line."""
        first = _run(fake_repo, fake_uv_bin, "success")
        assert first.returncode == 0, first.stderr
        first_lock = (fake_repo / "requirements.lock").read_text(encoding="utf-8")

        second = _run(fake_repo, fake_uv_bin, "success")
        assert second.returncode == 0, second.stderr
        second_lock = (fake_repo / "requirements.lock").read_text(encoding="utf-8")

        assert first_lock == second_lock

    @pytest.mark.parametrize(
        "scenario",
        [
            "missing_header",
            "wrong_banner",
            "missing_o_flag",
            "trailing_after_o",
            "empty_o_value",
            "duplicate_header",
            "header_moved",
            "unexpected_third_header",
        ],
    )
    def test_malformed_header_fails_closed_and_does_not_write_lock(
        self, fake_repo: Path, fake_uv_bin: Path, scenario: str
    ):
        result = _run(fake_repo, fake_uv_bin, scenario)
        assert result.returncode != 0, (
            f"scenario={scenario!r} unexpectedly succeeded: stdout={result.stdout!r}"
        )
        assert "compile_lock.sh:" in result.stderr
        assert not (fake_repo / "requirements.lock").exists(), (
            f"scenario={scenario!r} left a lock file behind despite failing"
        )


class TestVerifyModeHeaderContract:
    def _seed_valid_lock(self, fake_repo: Path, fake_uv_bin: Path) -> None:
        result = _run(fake_repo, fake_uv_bin, "success")
        assert result.returncode == 0, result.stderr

    def test_verify_passes_when_committed_header_is_canonical(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        self._seed_valid_lock(fake_repo, fake_uv_bin)
        result = _run(fake_repo, fake_uv_bin, "success", mode="--verify")
        assert result.returncode == 0, result.stderr
        assert "--verify PASS" in result.stdout

    def test_verify_fails_when_committed_header_is_tampered(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        """CR-HCI4-MAJ-01's core gap: body-only comparison let a tampered
        committed header pass `--verify` silently. The committed lock's
        body must still match, but its header line 2 must not be an
        arbitrary/stale value."""
        self._seed_valid_lock(fake_repo, fake_uv_bin)
        lock_path = fake_repo / "requirements.lock"
        lock_text = lock_path.read_text(encoding="utf-8")
        tampered = lock_text.replace(
            _canonical_line2(),
            f"{CANONICAL_PREFIX}/tmp/tmp.someStaleScratchPath",
        )
        assert tampered != lock_text
        lock_path.write_text(tampered, encoding="utf-8")

        result = _run(fake_repo, fake_uv_bin, "success", mode="--verify")
        assert result.returncode != 0
        assert "header" in result.stderr.lower()

    def test_verify_fails_when_committed_banner_is_tampered(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        self._seed_valid_lock(fake_repo, fake_uv_bin)
        lock_path = fake_repo / "requirements.lock"
        lock_text = lock_path.read_text(encoding="utf-8")
        tampered = lock_text.replace(CANONICAL_LINE1, "# hand-edited lock file")
        assert tampered != lock_text
        lock_path.write_text(tampered, encoding="utf-8")

        result = _run(fake_repo, fake_uv_bin, "success", mode="--verify")
        assert result.returncode != 0
        assert "header" in result.stderr.lower()

    def test_verify_fails_when_committed_lock_has_unexpected_third_header_line(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        """CR-HCI4-I2-MAJ-01: `canonical_body()` strips every leading `#`
        line before the body-hash comparison, so an arbitrary extra comment
        inserted at line 3 of the committed lock survived `--verify` as
        long as line 1/2 stayed canonical and the eventual body matched.
        `validate_committed_header()` must reject it directly instead of
        letting it disappear into the stripped header."""
        self._seed_valid_lock(fake_repo, fake_uv_bin)
        lock_path = fake_repo / "requirements.lock"
        lines = lock_path.read_text(encoding="utf-8").splitlines(keepends=True)
        assert lines[0] == f"{CANONICAL_LINE1}\n"
        tampered_lines = lines[:2] + ["# unexpected third header line\n"] + lines[2:]
        lock_path.write_text("".join(tampered_lines), encoding="utf-8")

        result = _run(fake_repo, fake_uv_bin, "success", mode="--verify")
        assert result.returncode != 0
        assert "header" in result.stderr.lower()

    def test_verify_fails_when_committed_banner_is_duplicated(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        """CR-HCI4-I2-MAJ-01: a second copy of the canonical autogenerated-by
        banner appended after the real header is itself just another
        `#`-prefixed line and must be rejected the same way as any other
        unexpected third header line, not silently stripped by
        `canonical_body()`."""
        self._seed_valid_lock(fake_repo, fake_uv_bin)
        lock_path = fake_repo / "requirements.lock"
        lines = lock_path.read_text(encoding="utf-8").splitlines(keepends=True)
        assert lines[0] == f"{CANONICAL_LINE1}\n"
        assert lines[1] == f"{_canonical_line2()}\n"
        tampered_lines = lines[:2] + [lines[0], lines[1]] + lines[2:]
        lock_path.write_text("".join(tampered_lines), encoding="utf-8")

        result = _run(fake_repo, fake_uv_bin, "success", mode="--verify")
        assert result.returncode != 0
        assert "header" in result.stderr.lower()


class TestSeedingDurabilityAgainstUnpinnedTransitiveDrift:
    """Hosted_CI_Remediation_Iteration_6.md — `compile_once()` used to
    always compile into a blank `mktemp` file, so `uv pip compile` had no
    existing-output-file preference to honor and always re-resolved every
    unpinned transitive dependency to whatever was newest on the index at
    that exact moment (how `langsmith` silently drifted from the committed
    0.10.18 to a newer release with zero requirements.txt change). The
    fix seeds each compile target with the currently committed
    `requirements.lock` first, when one already exists."""

    def test_first_ever_compile_has_no_lock_to_seed_from(self, fake_repo: Path, fake_uv_bin: Path):
        assert not (fake_repo / "requirements.lock").exists()
        result = _run(fake_repo, fake_uv_bin, "record_preseed")
        assert result.returncode == 0, result.stderr
        lock_text = (fake_repo / "requirements.lock").read_text(encoding="utf-8")
        assert "PRESEED_LEN:EMPTY" in lock_text

    def test_recompile_seeds_uv_invocation_with_committed_lock_content(
        self, fake_repo: Path, fake_uv_bin: Path
    ):
        committed = (
            f"{CANONICAL_LINE1}\n{_canonical_line2()}\n"
            "some-transitive-pkg==1.2.3 \\\n"
            "    --hash=sha256:deadbeef\n"
        )
        (fake_repo / "requirements.lock").write_text(committed, encoding="utf-8")

        result = _run(fake_repo, fake_uv_bin, "record_preseed")
        assert result.returncode == 0, result.stderr
        lock_text = (fake_repo / "requirements.lock").read_text(encoding="utf-8")
        assert f"PRESEED_LEN:{len(committed.encode('utf-8'))}" in lock_text
        # Compile mode's own reproducibility self-check (tmp_a vs tmp_b,
        # both produced by two separate `compile_once` calls) already
        # passed (returncode 0 above) — if the two passes had seen
        # different preseed content, their bodies would disagree and the
        # script would have failed with "lock is not reproducible"
        # instead, so this single assertion also proves both passes were
        # seeded identically.
